### ISSUE TITLE
Handling URL Hacking Nicer

### ISSUE THREAD

**Issue by JonathanShor** [TheFiggisAgency/placeholder_here#11]
Currently, URL hacking to an invalid course/student/whatever leads to the "oh no" screen. Should likely either handle specific hacks better, or at least have a link from the "oh no" screen back to the front page to restart.

**Comment by rivertam** [comment]
The idiomatic way to do this is to just serve a 404. The best way to think of a resource routing scheme is like a forum.

```
/ # home page
/boards # index of boards
/boards/mechanics # The "mechanics" board (in Rails, this would be referred to as the "show" page)
/boards/mechanics/posts # An index of the posts in the mechanics board (might be the same as the show page, in this case, because a board is probably very little more than a list of posts)
/boards/mechanics/posts/123456 # One particular post
/boards/mechanics/posts/123456/comments # the comments section (index of comments)
/boards/mechanics/posts/123456/comments/654321 # one particular comment
```

So you can imagine `/boards/doesnt-exist` is a resource that doesn't exist, or cannot be found. Technically the resource could exist but the user doesn't have permission to see it or even know that it exists. Either way, we want to tell the user that there's nothing there, and that's what 404 is.

----

I think the "oh no" screen only applies to 500s right now, so this change would require fixing an error... lol

**Comment by JonathanShor** [comment]
That makes sense. Tho I think the application is a little different than a forum, in so far as the user experiences it much more interactively than a forum (which is more passive).

I stuck the Go Home link on the error page, so at least if someone foolishly bookmarked a page that later becomes invalid, they have an obvious way to proceed.
